apiVersion: apps/v1
kind: Deployment
metadata:
  name: obot-deployment
  namespace: obot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: obot
    spec:
      containers:
        - name: obot-container
          image: jonathanmdr/obot:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: obot-secret
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 2Gi
  selector:
    matchLabels:
      app: obot
