apiVersion: apps/v1
kind: Deployment
metadata:
  name: obot-deployment
  namespace: obot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: obot
    spec:
      containers:
        - name: obot-container
          image: jonathanmdr/obot:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: obot-secret
          resources:
            requests:
              cpu: 128m
              memory: 500Mi
            limits:
              cpu: 256m
              memory: 1Gi
  selector:
    matchLabels:
      app: obot
